services:  
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: 'laravelapp'
    ports:
      - 8083:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    container_name: 'bthere_mysql'
    ports: 
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8084:80